/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Login
         * @description Redirects the user to the login form for authentik (if not signed in already)
         */
        get: operations["login_auth_login_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/callback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Callback
         * @description Stores session token in server-side session. Should redirect to original page
         */
        get: operations["callback_auth_callback_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Getusers
         * @description Returns a list of users (todo: based on the current users view permissions)
         */
        get: operations["getUsers_users_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * PartialGroup
         * @description Partial Group Serializer, does not include child relations.
         */
        PartialGroup: {
            /**
             * Pk
             * Format: uuid
             */
            pk: string;
            /**
             * Num Pk
             * @description Get a numerical, int32 ID for the group
             */
            num_pk: number;
            /** Name */
            name: string;
            /**
             * Is Superuser
             * @description Users added to this group will be superusers.
             */
            is_superuser?: boolean | null;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * Role
         * @description Role serializer
         */
        Role: {
            /**
             * Pk
             * Format: uuid
             */
            pk: string;
            /** Name */
            name: string;
        };
        /**
         * User
         * @description User Serializer
         */
        User: {
            /** Pk */
            pk: number;
            /** Username */
            username: string;
            /**
             * Name
             * @description User's display name.
             */
            name: string;
            /**
             * Is Active
             * @description Designates whether this user should be treated as active. Unselect this instead of deleting accounts.
             */
            is_active?: boolean | null;
            /** Last Login */
            last_login?: string | null;
            /**
             * Date Joined
             * Format: date-time
             */
            date_joined: string;
            /** Is Superuser */
            is_superuser: boolean;
            /** Groups */
            groups?: string[] | null;
            /** Groups Obj */
            groups_obj: components["schemas"]["PartialGroup"][] | null;
            /** Roles */
            roles?: string[] | null;
            /** Roles Obj */
            roles_obj: components["schemas"]["Role"][] | null;
            /** Email */
            email?: string | null;
            /**
             * Avatar
             * @description User's avatar, either a http/https URL or a data URI
             */
            avatar: string;
            /** Attributes */
            attributes?: {
                [key: string]: unknown;
            } | null;
            /** Uid */
            uid: string;
            /** Path */
            path?: string | null;
            type?: components["schemas"]["UserTypeEnum"] | null;
            /**
             * Uuid
             * Format: uuid
             */
            uuid: string;
            /**
             * Password Change Date
             * Format: date-time
             */
            password_change_date: string;
            /**
             * Last Updated
             * Format: date-time
             */
            last_updated: string;
        };
        /**
         * UserTypeEnum
         * @description UserTypeEnum
         * @enum {string}
         */
        UserTypeEnum: "internal" | "external" | "service_account" | "internal_service_account";
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login_auth_login_get: {
        parameters: {
            query: {
                current_url: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    callback_auth_callback_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    getUsers_users_get: {
        parameters: {
            query?: {
                attributes?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
