import { ThemeProvider } from "@/components/theme-provider";
import { AppSidebar } from "@/components/ui/main/app-sidebar";
import { SAWView } from "@/components/ui/main/saw-view";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    const data = {
        navMain: [
            {
                title: "EWash",
                url: "/ewash",

                items: [
                    {
                        title: "Booking",
                        url: "/ewash",
                    },
                    {
                        title: "Maintenance",
                        url: "/ewash/maintenance",
                    },
                    {
                        title: "Sellers",
                        url: "/ewash/sellers",
                    },
                    {
                        title: "SAW-Coin",
                        url: "/ewash/saw-coin",
                        items: [
                            {
                                title: "Overview",
                                url: "/ewash/saw-coin",
                            },
                            {
                                title: "Account",
                                url: "/ewash/saw-coin/account",
                            },
                            {
                                title: "Seller",
                                url: "/ewash/saw-coin/seller",
                            },
                            {
                                title: "Finances",
                                url: "/ewash/saw-coin/finances",
                            },
                            {
                                title: "Admin",
                                url: "/ewash/saw-coin/admin",
                            },
                        ],
                    },
                ],
            },
            {
                title: "Settings",
                url: "/settings",
                items: [
                    {
                        title: "Profile",
                        url: "/settings/profile",
                    },
                ],
            },
        ],
    };

    return (
        <>
            <html lang="en" suppressHydrationWarning>
                <head />
                <body>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <SidebarProvider>
                            <AppSidebar data={data} />
                            <SidebarInset className="w-full bg-muted p-5">
                                <SAWView navigationData={data}>
                                    {children}
                                </SAWView>
                            </SidebarInset>
                        </SidebarProvider>
                    </ThemeProvider>
                </body>
            </html>
        </>
    );
}
